#ifndef GOSUB_H
#define GOSUB_H

/* Warning: This file is auto-generated by cbindgen. Do not edit manually! */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Engine Engine;

typedef struct GosubEngineHandle {
  struct Engine *_0;
} GosubEngineHandle;

struct GosubEngineHandle gosub_engine_new(void);

void gosub_load_url(struct GosubEngineHandle handle, const char *url);

bool gosub_tick(struct GosubEngineHandle handle);

uintptr_t gosub_render(struct GosubEngineHandle handle, uint8_t *output, uintptr_t output_size);

void gosub_engine_free(struct GosubEngineHandle handle);

#endif  /* GOSUB_H */
