[package]
name = "gosub_renderer"
version = "0.1.0"
edition = "2021"
authors = ["Gosub Community <info@gosub.io>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gosub_rendering = { path = "../gosub_render_utils" }
gosub_html5 = { path = "../gosub_html5" }
gosub_shared = { path = "../gosub_shared" }
gosub_styling = { path = "../gosub_styling" }
gosub_net = { path = "../gosub_net" }
gosub_render_backend = { path = "../gosub_render_backend" }
taffy = "0.5.1"
anyhow = "1.0.86"
image = "0.25.1"
url = "2.5.0"
rand = { version = "0.9.0-alpha.1", features = [] }



[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.42"
web-sys = "0.3.55"
